INSERT INTO director (firstname, lastname) VALUES
('Steven', 'Spielberg'),
('Martin', 'Scorsese'),
('Quentin', 'Tarantino'),
('Christopher', 'Nolan'),
('James', 'Cameron'),
('Ridley', 'Scott'),
('Francis Ford', 'Coppola'),
('Stanley', 'Kubrick'),
('Alfred', 'Hitchcock'),
('Peter', 'Jackson'),
('Clint', 'Eastwood'),
('Tim', 'Burton'),
('David', 'Fincher'),
('George', 'Lucas'),
('Woody', 'Allen'),
('Sofia', 'Coppola'),
('Guillermo', 'del Toro'),
('Wes', 'Anderson'),
('Spike', 'Lee'),
('Alejandro', 'González Iñárritu');